version: '3'
services:
  emanager_nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./runserv/nginx.conf:/etc/nginx/nginx.conf
      - ./media:/source/media
      - ./static:/source/static
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - emanager_app

  emanager_db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    env_file:
      - .env
    volumes:
      - ./runserv/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  emanager_app:
    container_name: emanager
    build:
      context: .
      dockerfile: runserv/Dockerfile
    restart: always
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=emanager.lvh.me
      - DB_DATABASE=event_manager
      - DB_HOST=emanager_db
      - DB_PORT=5432
      - DB_PASSWORD=em1111
      - DB_USER=emanager
    volumes:
      - .:/source
    ports:
      - "8000:8080"
    depends_on:
      - emanager_db
      - redis

  redis:
    image: redis:alpine
    container_name: redis