version: '3'
services:
  emanager_nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./runserv/nginx.conf:/etc/nginx/nginx.conf
      - ./event_manager/media:/source/event_manager/media
      - ./main/static:/source/main/static
    ports:
      - 81:80
      - 443:443
    depends_on:
      - emanager_app

  emanager_db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    env_file:
      - .env
    volumes:
      - ./runserv/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  emanager_app:
    container_name: emanager
    build:
      context: .
      dockerfile: runserv/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/source
    ports:
      - 8000:8000
    depends_on:
      - emanager_db
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379