# Generated by Django 3.1.4 on 2021-05-29 20:49

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to=main.models.event.files_upload, verbose_name='Файлы события'), size=10),
        ),
    ]
