# Generated by Django 3.1.4 on 2021-05-31 21:12

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models.event
import main.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210529_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=main.models.event.files_upload, verbose_name='Файлы события'), size=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user.profile_upload, verbose_name='Картинка профиля'),
        ),
    ]
