#!/bin/sh
set -e

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE USER ${DB_USER} WITH SUPERUSER PASSWORD '${DB_PASSWORD}';" &&\
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE ${DB_DATABASE} WITH OWNER ${DB_USER};" &&\
psql -U "$DB_USER" -d "$DB_DATABASE" -c "CREATE EXTENSION citext;"